version: '3'
services:
  dev-db:
    image: postgres:13
    container_name: dev-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: users
    networks:
      - kamers
networks:
  kamers: