apiVersion: v1
kind: Service
metadata:
  name: prisma-db
spec:
  type: LoadBalancer
  selector:
    app: prisma-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prisma-db
spec:
  selector:
    matchLabels:
      app: prisma-db
  template:
    metadata:
      labels:
        app: prisma-db
    spec:
      containers:
      - name: prisma-db
        image: stylo2k/kamer-db:latest
        env: # TODO: convert to envFrom
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "123"
        - name: POSTGRES_DB
          value: users
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432

